BCS/Controllers/EmployeesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using BCS.Application.Entity;
using BCS.Application.Domain;
using BCS.Application.Service;
using BCS.Models;
using BCS.Helper;
using PagedList;
using System.Text;
using System.Net.Http;
using System.Web.Helpers;
using BCS.HtmlHelpers;

namespace BCS.Controllers
{
    public class EmployeesController : Controller
    {
        readonly IEmployeeRepositoy _empRepo;
        readonly ILogRepository _logRepo;
        readonly IMonitor _monitoring;

        public EmployeesController(IEmployeeRepositoy empRepo, ILogRepository logRepository, IMonitor monitoring)
        {
            _empRepo = empRepo;
            _logRepo = logRepository;
            _monitoring = monitoring;
        }

        private void LogActivity(string operation, string message){
            ActivityLoggingService logService = new ActivityLoggingService(_logRepo, _monitoring);
            logService.LogActivity(operation, message);
        }

        [System.Web.Mvc.Authorize(Roles = "Admin, Editor, Viewer")]
        public ActionResult Index(){
            return View();
        }

        [System.Web.Mvc.Authorize(Roles = "Admin, Editor, Viewer")]
        public JsonResult Search(int? page, int? pageSize, string orderBy, string orderByColumn, string search)
        {
            HttpContext.Response.AppendHeader("Access-Control-Allow-Origin", "*");
            EmployeePage pageModel = new EmployeePage();

            try
            {
                MainUser u = _empRepo.GetByUserName(User.Identity.Name);
                SearchParam param = new SearchParam();
                param.CurrentPage = (page ?? 1) - 1;
                param.PageSize = pageSize ?? 5;
                param.OrderyBy = orderBy == "Descending" ? OrderyBy.Descending : OrderyBy.Ascending;
                param.OrderbyCriteria = SetOrderByColumn(orderByColumn);
                param.Search = search;

                UserService service = new UserService(_empRepo);
                SearchResult result = service.GetAllUser(u.UserName, param);
                pageModel = UserHelper.MapResultToEmployeePageModel(result);
                pageModel.IsAdmin = (u.UserType == UserType.Admin);
                pageModel.ShouldDisplayAddAndEdit = (u.UserType == UserType.Admin || u.UserType == UserType.Editor);

            }
            catch (Exception ex)
            {
                string message = ex.Message;
            }

            return Json(pageModel, JsonRequestBehavior.AllowGet);
        }

        private OrderbyCriteria SetOrderByColumn(string column)
        {
            OrderbyCriteria criteria = OrderbyCriteria.Id;
            if (column == "Id")
            {
                criteria = OrderbyCriteria.Id;
            }
            else if (column == "HireDate")
            {
                criteria = OrderbyCriteria.HireDate;
            }
            else if (column == "Department")
            {
                criteria = OrderbyCriteria.Department;
            }
            else if (column == "Alphabetical")
            {
                criteria = OrderbyCriteria.Alphabetical;
            }

            return criteria;
        }

        [System.Web.Mvc.Authorize(Roles = "Admin, Editor")]
        [ValidateAntiForgeryHeader]
        [HttpPost]
        public JsonResult AddPerson(AddUserModel model)
        {
            HttpContext.Response.AppendHeader("Access-Control-Allow-Origin", "*");

            EmployeeStatusResult result = new EmployeeStatusResult();
            try
            {
                var uToAdd = UserHelper.MapAddUserModelToUser(model);
                uToAdd.Password = "default";
                uToAdd.IsActive = true;
                uToAdd.AddedDate = DateTime.Now;
                _empRepo.Add(uToAdd);
                result.Success = true;
                result.Message = "User Added";
                LogActivity("Add User", uToAdd.UserName + " is added by " + User.Identity.Name);
            }
            catch (Exception ex)
            {
                result.Success = false;
                result.Message = CreateExceptionMessage(ex);
            }

            return Json(result, JsonRequestBehavior.AllowGet);
        }

        [Authorize]
        [HttpGet]
        public JsonResult GetUserById(long id)
        {
            HttpContext.Response.AppendHeader("Access-Control-Allow-Origin", "*");
            var emp = _empRepo.GetById(id);
            EditUserModel model = UserHelper.MapUserToEditUserModel(emp);

            return Json(model, JsonRequestBehavior.AllowGet);
        }

        public ActionResult EditUser(){
            return View();
        }

        [ValidateAntiForgeryHeader]
        [System.Web.Mvc.Authorize(Roles = "Admin, Editor")]
        [HttpPost]
        public JsonResult EditUser(EditUserModel model)
        {
            HttpContext.Response.AppendHeader("Access-Control-Allow-Origin", "*");
            EmployeeStatusResult result = new EmployeeStatusResult();
            try
            {
                var u = UserHelper.MapEditUserModelToUser(model);
                _empRepo.Edit(u);
                result.Success = true;
                result.Message = "User Edited";
                LogActivity("Edit User", model.UserName + " is edited by " + User.Identity.Name);
            }
            catch (Exception ex)
            {
                result.Success = false;
                result.Message = CreateExceptionMessage(ex);
            }

            return Json(result, JsonRequestBehavior.AllowGet);
        }

        //[System.Web.Mvc.Authorize(Roles = "Admin, Editor, Viewer")]
        //public ActionResult Details(long id)
        //{
        //    MainUser u = _empRepo.GetById(id);
        //    DetailUserModel model = UserHelper.MapUserToDetailUserModel(u);

        //    return View(model);
        //}

        [System.Web.Mvc.Authorize(Roles = "Admin, Editor, Viewer")]
        public JsonResult Details(long id)
        {
            HttpContext.Response.AppendHeader("Access-Control-Allow-Origin", "*");
            MainUser u = _empRepo.GetById(id);
            DetailUserModel model = UserHelper.MapUserToDetailUserModel(u);

            return Json(model, JsonRequestBehavior.AllowGet);
        }

        [System.Web.Mvc.Authorize]
        public ActionResult EditProfile()
        {
            MainUser currentUser = _empRepo.GetByUserName(User.Identity.Name);
            EditProfileModel model = UserHelper.MapUserToEditProfileModel(currentUser);
            model.Countries = GetCountries();
            return View(model);
        }

        [System.Web.Mvc.Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditProfile(EditProfileModel model)
        {
            if (ModelState.IsValid)
            {
                MainUser currentUser = UserHelper.MapEditProfileModelToUser(model);
                currentUser.UserName = User.Identity.Name;

                _empRepo.EditProfile(currentUser);

                return RedirectToAction("Index", "Home");
            }
            model.Countries = GetCountries();

            return View();
        }

        [System.Web.Mvc.Authorize(Roles = "Admin, Editor")]
        [ValidateAntiForgeryHeader]
        public bool Disable(long id)
        {
            _empRepo.Disable(id);
            var emp = _empRepo.GetById(id);

            LogActivity("Disable User", emp.UserName + " is Disabled by " + User.Identity.Name);
            return true;
        }

        [System.Web.Mvc.Authorize(Roles = "Admin, Editor")]
        [ValidateAntiForgeryHeader]
        public bool Enable(long id)
        {
            _empRepo.Enable(id);
            var emp = _empRepo.GetById(id);

            LogActivity("Enable User", emp.UserName + " is Enabled by " + User.Identity.Name);
            return true;
        }

        [System.Web.Mvc.Authorize(Roles = "Admin")]
        [ValidateAntiForgeryHeader]
        public bool Unlock(long id)
        {
            MainUser uToUnlock = _empRepo.GetById(id);
            if (uToUnlock != null)
            {
                _empRepo.Unlock(uToUnlock.UserName);
                LogActivity("Unlock User", uToUnlock.UserName + " is Unlocked by " + User.Identity.Name);
                return true;
            }
            return false;
        }

        [System.Web.Mvc.Authorize(Roles = "Admin")]
        public FileContentResult DownloadAllUser()
        {
            CSVMaker maker = new CSVMaker(_empRepo);
            var data = Encoding.UTF8.GetBytes(maker.MakeEmployeeSCV());
            string filename = "users.csv";
            string mime = "text/csv";
            return File(data, mime, filename);
        }


        public JsonResult GetListOfCountry(){
            HttpContext.Response.AppendHeader("Access-Control-Allow-Origin", "*");

            var countries = GetCountries();
            return Json(countries, JsonRequestBehavior.AllowGet);
        }

        public List<Country> GetCountries()
        {
            string path = @"https://restcountries.eu/rest/v2/all";

            HttpClient client = new HttpClient();

            List<Country> countries = new List<Country>();
            string content = "";
            var response = client.GetAsync(path).GetAwaiter().GetResult();
            if (response.IsSuccessStatusCode)
            {
                content = response.Content.ReadAsStringAsync().GetAwaiter().GetResult();
            }

            countries = Newtonsoft.Json.JsonConvert.DeserializeObject<List<Country>>(content);

            return countries;
        }

        [HttpPost]

BCS/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="~/Content/stylesheet/bootstrap.css">
    <link rel="stylesheet" href="~/Content/stylesheet/jquery-ui.css">
    <link rel="stylesheet" href="~/Content/stylesheet/jquery-ui.structure.css">
    <link rel="stylesheet" href="~/Content/stylesheet/jquery-ui.theme.css">
    <link rel="stylesheet" href="~/Content/stylesheet/languagenav.css">
    <link rel="stylesheet" href="~/Content/stylesheet/secondnav.css">
    <link rel="stylesheet" href="~/Content/stylesheet/main.css">
    <link rel="stylesheet" href="~/Content/stylesheet/angular-bootstrap-toggle.min.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.2.0/css/all.css"
          integrity="sha384-hWVjflwFxL6sNzntih27bfxkr27PmbbK/iSvJ+a4+0owXq79v+lsFkW54bOGbiDQ" crossorigin="anonymous">

    <script src="~/Content/scripts/jquery.js"></script>
        <script src="~/Content/scripts/jquery-ui.js"></script>
        <script src="~/Content/scripts/bootstrap.js"></script>
        <script src="~/Content/scripts/main.js"></script>
        <script src="~/Content/scripts/login-modal.js"></script>

    <title>Title</title>
</head>
<body>
    <div id="myHeader">
        <nav class="navbar navbar-first navbar-inverse navbar-inverse-first">
            <div class="container">
                <div class="row">
                    <div class="navbar-header navbar-header-first">
                        <button type="button" class="pull-left navbar-toggle navbar-toggle-first" data-toggle="collapse"
                                data-target="#myNavbar">
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                    </div>

                    <div class="social-media-section pull-right">
                        <div class="right-social-media">
                            <i class="fab fa-twitter"></i>
                        </div>
                        <div class="right-social-media">
                            <i class="fab fa-facebook-f"></i>
                        </div>
                        <div class="right-social-media">
                            <i class="fab fa-google-plus-g"></i>
                        </div>
                        <div class="right-social-media">
                            <i class="fab fa-youtube"></i>
                        </div>
                    </div>
                    <div class="login-section pull-right">
                        @if (User.Identity.IsAuthenticated)
                        {
                            <div id="logout-link">
                                <label> Welcome: </label><span id="logon-name"> @Html.ActionLink(User.Identity.Name, "EditProfile", "Employees") </span>
                                <a href="@Url.Action("LogOut", "Home", null, Request.Url.Scheme)">Log-out</a>
                            </div>
                        }
                        else
                        {
                            <div id="login-link">
                                <a href="#" data-toggle="modal" data-target="#login-modal">Log-in</a>
                            </div>
                        }

                    </div>
                    <div class="collapse navbar-collapse navbar-collapse-first" id="myNavbar">
                        <ul class="nav navbar-nav navbar-nav-first pull-left" id="top-language">
                            <li><a href="#">SPANISH</a></li>
                            <li><a href="#">PORTUGUESE</a></li>
                            <li><a href="#">ENGLISH</a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </nav>
    </div>
    <header>
        <div class="container">
            <a href="#"><img src="~/Content/image/angdatingdaan-website-logo-blue-wide.png"></a>
        </div>
    </header>
    <div class="second-navigation">
        <nav class="navbar navbar-second navbar-inverse navbar-inverse-second">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar2">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                </div>
                <div class="collapse navbar-collapse navbar-collapse-second" id="myNavbar2">
                    <ul class="nav nav-second navbar-nav navbar-nav-second">
                        <li class="active"><a href="#"><i class="fas fa-home"></i></a></li>
                        @if (Request.IsAuthenticated && (User.IsInRole("Admin") || User.IsInRole("Editor") || User.IsInRole("Viewer")))
                        {
                        <li><a href="@Url.Action("Index", "Employees", null, Request.Url.Scheme)"><i class="fas fa-book"></i> Employees</a></li>
                        }
                        <li>
                            <a href="#">
                                <i class="fas fa-less-than"></i>
                                <i class="fas fa-greater-than"></i> DEBATE
                            </a>
                        </li>
                        <li><a href="#"><i class="fas fa-info-circle"></i> TUNGKOL SA PROGRAMA</a></li>
                        <li><a href="#"><i class="fas fa-mobile-alt"></i> CONTACT US</a></li>
                        <li class="black"><a href="#"><i class="fas fa-tv"></i> LIVE EVENTS</a></li>
                    </ul>
                    <ul class="nav navbar-nav navbar-nav-second navbar-right">
                        <li class="navy-blue"><a href="#"><i class="fas fa-search"></i></a></li>
                    </ul>
                </div>
            </div>
        </nav>
    </div>
    <section id="main-content" class="container">
        <div class="news-head">
            <div class="news-left-blue">
                <span>BAGONG VIDEO</span>
            </div>
            <div class="news-middle">
            </div>
            <div class="news-time">
                7:36
            </div>
        </div>
        <div class="row">
            <div class="content-section col-lg-9 col-md-8">
                @RenderBody()

            </div>
            <div class="side-tweets col-lg-3 col-md-4">
                <div class="tweets">
                    Is There a Scientific Way of Discovering Biblical Truth? (Part 2) #SpecialNationOfGod
                    https://t.co/LFrPs6Agbb
                </div>
                <div class="tweets">CNN is this now their way of making themselves famous?!</div>
                <div class="tweets">
                    Is There a Scientific Way of Discovering Biblical Truth? (Part 1)
                    #GodAppointsChurchLeaders https://t.co/nW5JDVOwF3
                </div>
                <div class="tweets">
                    What to Do When it Feels Like God Is Far Away? https://t.co/dI8GVSJVVB
                    #GodIsNeverFarFromUs
                </div>
            </div>
        </div>
    </section>
    <div class="footer-section">
        <div class="footer-first"></div>
        <div class="footer-second">
            <div class="container">
                <div class="footer-about col-lg-10">
                    <span class="about">
                        © 2014-2018 Produced through the help of ALMIGHTY GOD by the <a href="#"> members of Church of God Internation</a> ® | <a href="#">Our Privacy Policy</a> | <a href="#">Contact us</a>
                    </span>
                </div>
                <div class="footer-social-media col-lg-2">
                    <div class="right-social-media social-media-big">
                        <i class="fab fa-twitter"></i>
                    </div>
                    <div class="right-social-media social-media-big">
                        <i class="fab fa-facebook-f"></i>
                    </div>
                    <div class="right-social-media social-media-big">
                        <i class="fab fa-google-plus-g"></i>
                    </div>
                    <div class="right-social-media social-media-big">
                        <i class="fab fa-youtube"></i>
                    </div>
                </div>
            </div>
        </div>
    </div>

    @{Html.RenderPartial("_loginview", new BCS.Identity.LoginModel());}

</body>
</html>

BCS/Views/Shared/_loginview.cshtml
@model BCS.Identity.LoginModel

    <div class="modal fade" id="login-modal" tabindex="-1" role="dialog" aria-labelledby="login-modalLabel">
        <div class="modal-dialog" role="document">
            <div class="modal-content modal-dialog-centered">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="login-modalLabel">Log-in</h4>
                </div>
                <div class="modal-body">
                    <span id="error-message" class="danger-red-text"></span>
                    <div class="form-group">
                        <label for="user-name-text" class="control-label">User name:</label>
                        @Html.TextBoxFor(m => m.UserName, new { @class = "form-control", @id = "user-name-text" })
                    </div>
                    <div class="form-group">
                        <label for="password-text" class="control-label">Password:</label>
                        @Html.PasswordFor(m => m.Password, new { @class = "form-control", @id = "password-text" })
                    </div>
                    <div class="form-group">
                        @Html.CheckBoxFor(m => m.RememberMe, new { @class = "", @id = "remember-me-check" })
                        @Html.LabelFor(m => m.RememberMe)
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    <button type="button" id="login-button" class="btn btn-primary">Log-in</button>
                </div>
            </div>
        </div>
    </div>
